services:
  - type: web
    name: superbot-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_USER
        value: sql12791893
      - key: DB_PASSWORD
        value: 3ALYm8PAgb
      - key: DB_NAME
        value: sql12791893
      - key: DB_PORT
        value: 3306
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production 